---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: grumbeer-os
# description will be included in the image's metadata
description: My personal experiment in making my own custom linux.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/niri
image-version: latest # latest is also supported if you want new updates ASAP

# stages:
# https://blue-build.org/reference/recipe/#stages
# https://blue-build.org/reference/stages/

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - scottames/ghostty
        - zawertun/hack-fonts
        - che/nerd-fonts
        - mineori/satty
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
    install:
      packages:
        # scottames/ghostty
        - ghostty
        
        # zawertun/hack-fonts
        - hack-fonts

        # che/nerd-fonts
        - nerd-fonts

        # mineiro/satty
        - satty

        # terra
        - noctalia-shell

        # fedora
        - npm
        - helix
        - fish
        - entr
        - fd
        - bat
        - npm

    remove:
      packages:
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - toolbox
        - waylock

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install:
          # system flatpaks we want all users to have and not remove
          # generically useful
          - com.github.tchx84.Flatseal
          - com.valvesoftware.Steam
          - org.mozilla.firefox
          - it.mijorus.gearlever
          - org.kde.gwenview
          - org.kde.okular
          - org.libreoffice.LibreOffice
          - org.videolan.VLC
          - org.kde.kcharselect
          - io.github.vemonet.EmojiMart

          # personal crap
          - net.cozic.joplin_desktop
          - org.signal.Signal
          - one.ablaze.floorp
          - io.github.ungoogled_software.ungoogled_chromium
          - com.bitwarden.desktop
          - com.mastermindzh.tidal-hifi
          - com.nextcloud.desktopclient.nextcloud
          - com.github.wwmm.easyeffects

  - type: chezmoi
    repository: "https://codeberg.org/PotatoesFall/chezmoi" # my dotfiles repo
    all-users: true # make users have to enable chezmoi manually
    file-conflict-policy: replace # override changed files with those from the repo

  - type: os-release
    properties:
      ID: grumbeer_os
      NAME: GrumbeerOS
      PRETTY_NAME: GrumbeerOS
      DEFAULT_HOSTNAME: grumbeer

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
